config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  # OmniAuthの認証が成功したときに、コールバックとしてUsers::OmniauthCallbacksControllerが呼び出されるようにする設定
  root "static_pages#top" # TOPページ

  get "terms", to: "static_pages#terms" # 利用規約
  get "privacy", to: "static_pages#privacy" # プライバシーポリシー

  resources :posts, only: %i[index new create show edit destroy update] do # 投稿一覧,新規投稿,投稿詳細,編集,削除,更新
    collection do # postリソース全体にアクションを追加(IDがない)
      get :favorites # GET posts/favorites お気に入りされている投稿の一覧を出す
    end
  end

  resources :favorites, only: %i[create destroy] # お気に入り機能

  # 店舗検索用エンドポイント（Ajax用）
  resources :shops, only: [] do
    collection do # 全ての店舗から検索
      get :search_place # GET /shops/search_place?query=店舗名
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # プロフィール
  resources :profiles, only: %i[show edit update]

  # 開発環境でのメール確認
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
    @user = User.includes(:posts, :favorite_posts).find(params[:id])
    # 他の人のプロフィールも見れるようにする
    # favorite_postsを追加
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user

    begin
      # 画像を処理して更新
      @user.profile_image = @user.process_and_transform_image(params[:user][:profile_image], 400) if params[:user][:profile_image].present?

      if @user.update(profile_params)
        redirect_to profile_path, notice: t("defaults.flash_message.updated", item: User.model_name.human), status: :see_other
      else
        flash.now[:alert] = t("defaults.flash_message.not_updated", item: User.model_name.human)
        render :edit, status: :unprocessable_entity
      end

      rescue ImageProcessable::ImageProcessingError => e
        flash.now[:alert] = e.message
        render :edit
      end
  end

  private

  def profile_params
    params.require(:user).permit(:nickname, :region, :introduction)
    # profile_imageはwebpが上書きされてしまうので含めない
  end
end

app/views/profiles/edit.html.erb
<!-- プロフィール編集 -->
<div class="container mx-auto px-4 py-6">
  <h1 class="text-2xl font-bold mb-6"><%= t('.title') %></h1>

  <!-- 入力フォーム -->
<%# local: true ← Turbo Drive で送信しない（通常の form 送信）%>
<%# 更新処理をしたいから profile_path %>
<%= form_with model: @user, url: profile_path, local: true do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
    <div class="bg-secondary text-base p-4 pb-20 w-full">

      <!-- 名前 -->
      <div class="form-control mb-4">
        <%= f.label :nickname, class: "label-accent" do%>
          <%= f.object.class.human_attribute_name(:nickname) %>
        <% end %>
        <%= f.text_field :nickname, class: "input input-primary bg-neutral w-full" %>
      </div>

      <!-- 居住地 -->
      <div class="form-control mb-4">
        <%= f.label :region, class: "label-accent" do%>
          <%= f.object.class.human_attribute_name(:region) %>
        <% end %>
        <%= f.text_field :region, class: "input input-primary bg-neutral w-full", placeholder: "例: 東京都" %>
      </div>

      <!-- 画像 -->
      <div class="form-control mb-4">
        <legend class="fieldset-legend font-normal">プロフィール画像</legend>
          <%= f.file_field :profile_image, class: "file-input file-input-primary file:text-neutral bg-neutral w-full",
                                   accept: Post::ACCEPTED_CONTENT_TYPES.join(',') %>
            <label class="label">
              <span class="text-xs md:text-sm">JPEG、PNG、GIF、WebP、HEIC形式（10MB以下）の画像</span>
            </label>
      </div>

      <!-- 自己紹介 -->
      <div class="form-control mb-4">
        <%= f.label :introduction, class: "label-accent" %>
        <%= f.text_area :introduction, class: "textarea textarea-primary bg-neutral w-full", rows: "4" %>
      </div>

      <!-- 投稿ボタン -->
      <div class="form-control mt-6">
        <%= f.submit t('.submit'), class: "btn btn-primary text-neutral w-full" %>
      </div>
    </div>
<% end %>


</div>

app/views/profiles/show.html.erb
<div class="container mx-auto px-4 py-6 pb-20">
    <h1 class="text-2xl font-bold mb-6"><%= t('.title') %></h1>
<!-- 自分のプロフィール -->
  <div class="p-4 w-full" >
  <!-- 左右２カラムにする親 -->
  <div class="flex gap-5 mx-auto items-start">
    <!--　縦に並べる -->
    <div class="flex flex-col">
      <!-- アバター -->
      <div class="sm:mt-1">
        <div class="w-20 h-20 rounded-full overflow-hidden bg-neutral text-primary flex items-center justify-center">
          <% if @user.profile_image.attached? %>
            <%= image_tag(@user.profile_image, alt: "#{@user.nickname.present? ? @user.nickname : @user.username}さんのプロフィール画像", class: "w-full h-full rounded-full object-cover") %>
          <% else %>
          <svg xmlns="http://www.w3.org/2000/svg"
               viewBox="0 0 24 24" 
               fill="none" 
               stroke="currentColor" 
               stroke-width="2" 
               stroke-linecap="round" 
               stroke-linejoin="round"
               class="w-full h-full lucide lucide-circle-user-round-icon lucide-circle-user-round">
          <path d="M18 20a6 6 0 0 0-12 0"/>
          <circle cx="12" cy="10" r="4"/><circle cx="12" cy="12" r="10"/>
          </svg>
          <% end %>
        </div>
      </div>
      <!-- ユーザー名と編集 -->
      <div class= "flex items-center gap-1 mt-2">
        <span class="font-semibold text-xl"><%= @user.nickname.presence || @user.username %></span>
        <!-- 自分のマイページなら編集できる -->
        <% if @user == current_user %>
          <%= link_to edit_profile_path do %>
               <svg xmlns="http://www.w3.org/2000/svg" 
                    width="20" 
                    height="20" 
                    viewBox="0 0 24 24" 
                    fill="none" 
                    stroke="currentColor" 
                    stroke-width="2" 
                    stroke-linecap="round" 
                    stroke-linejoin="round" 
                    class="lucide lucide-pencil-icon lucide-pencil">
                  <path d="M21.174 6.812a1 1 0 0 0-3.986-3.987L3.842 16.174a2 2 0 0 0-.5.83l-1.321 4.352a.5.5 0 0 0 .623.622l4.353-1.32a2 2 0 0 0 .83-.497z"/>
                  <path d="m15 5 4 4"/>
                </svg>
          <% end %>
        <% end %>
      </div>

      <!-- 居住地 -->
      <div class= "flex items-center gap-1">
          <span class="font-semibold text-md">居住地：<%= @user.region.presence || "未設定" %></span>
      </div>
    </div>

    <!-- 右カラム：自己紹介 -->
  <div class="flex-1">
    <h2 class="font-semibold text-lg mb-2">自己紹介</h2>
    <div class="text-base break-all leading-normal">
      <%= @user.introduction.presence || "自己紹介がまだありません" %>
    </div>
  </div>
  </div>
  </div>

  <!-- 投稿一覧-->
  <div class="tabs tabs-lift tabs-lg font-semibold mt-2">
    <input type="radio" name="my_tabs_3" class="tab [--tab-bg:#F1D9E2] [--tab-border-color:#F1D9E2]" aria-label="投稿一覧" checked="checked" />
    <div class="tab-content bg-secondary p-6">
    <!-- 投稿カードグリッド -->
      <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-5 px-2">
        <%= render @user.posts %>
      </div>
    </div>

    <!-- お気に入りした投稿 -->
    <% if @user == current_user %>
      <input type="radio" name="my_tabs_3" class="tab [--tab-bg:#F1D9E2] [--tab-border-color:#F1D9E2]" aria-label="お気に入り投稿"/>
      <div class="tab-content bg-secondary p-6">
      <!-- お気に入りした投稿カードグリッド -->
        <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-5 px-2">
          <% if @user.favorite_posts.present? %>
            <%= render @user.favorite_posts %>
          <% else %>
            <p><%= t('.no_result') %></p>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>