config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  # OmniAuthの認証が成功したときに、コールバックとしてUsers::OmniauthCallbacksControllerが呼び出されるようにする設定
  root "static_pages#top" # TOPページ

  get "terms", to: "static_pages#terms" # 利用規約
  get "privacy", to: "static_pages#privacy" # プライバシーポリシー

  resources :posts, only: %i[index new create show edit destroy update] do # 投稿一覧,新規投稿,投稿詳細,編集,削除,更新
    collection do # postリソース全体にアクションを追加(IDがない)
      get :favorites # GET posts/favorites お気に入りされている投稿の一覧を出す
    end
  end

  resources :favorites, only: %i[create destroy] # お気に入り機能

  # 店舗検索用エンドポイント（Ajax用）
  resources :shops, only: [] do
    collection do # 全ての店舗から検索
      get :search_place # GET /shops/search_place?query=店舗名
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # プロフィール
  resources :profiles, only: %i[show edit update]

  # 開発環境でのメール確認
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/post.rb
class Post < ApplicationRecord
  include ImageProcessable # 画像処理
  validates :region, presence: true, length: { maximum: 5 }
  validates :shop_name, presence: true, length: { maximum: 28 }
  validates :rating, inclusion: { in: 1..5 }
  validates :body, length: { maximum: 500 }
  validates :is_pr, inclusion: { in: [ true, false ] }

  belongs_to :user
  belongs_to :shop, optional: true   # shop_idは任意
  has_one_attached :image # 画像投稿 # Rails が勝手に画像分析する必要はない
  has_one_attached :profile_image # プロフィール画像
  has_many :favorites, dependent: :destroy # お気に入り機能

  # Ransack で検索可能な属性を定義
  def self.ransackable_attributes(auth_object = nil)
    [ "body", "region", "shop_name" ]
  end

  # Ransack で検索可能な関連を定義
  def self.ransackable_associations(auth_object = nil)
    []
  end

  # ファイルの種類とサイズのバリデーション（gem ActiveStorage Validationを使用）
  ACCEPTED_CONTENT_TYPES = %w[
  image/jpeg
  image/png
  image/gif
  image/webp
  image/heic
  image/heif
].freeze

validates :image, content_type: ACCEPTED_CONTENT_TYPES,
                  size: { less_than_or_equal_to: 10.megabytes },
                  allow_blank: true
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :index, :show ]
  before_action :set_user_post, only: [ :edit, :update, :destroy ]
  # 自分の投稿かをチェック

  def index
    @search = Post.ransack(params[:q]) # 検索
    @posts = @search.result(distinct: true).includes(:user).with_attached_image.order(created_at: :desc) # 検索
  end

  def new
    @post = Post.new(rating: 3, is_pr: false)
  end
  # デフォルトで3点を設定

  def create
    setup_shop

    @post = current_user.posts.build(post_params)
    # Post オブジェクトを作成、DBには保存しない

    begin
      # 画像を処理して更新
      @post.image = @post.process_and_transform_image(params[:post][:image], 1200) if params[:post][:image].present?

      if @post.save
        redirect_to posts_path, notice: t("defaults.flash_message.created", item: Post.model_name.human), status: :see_other
      else
        flash.now[:alert] = t("defaults.flash_message.not_created", item: Post.model_name.human)
        render :new, status: :unprocessable_entity
        # エラーで422が返される
      end
    rescue ImageProcessable::ImageProcessingError => e
      flash.now[:alert] = e.message
      render :new
    end
  end

  def show
    @post = Post.includes(:user).find(params[:id])
  end

  def edit
    # @postは set_user_post で既にセット済み
  end

  def update
    setup_shop
    # @postは set_user_post で既にセット済み


    # 画像を処理して更新
    begin
      @post.image = @post.process_and_transform_image(params[:post][:image], 1200) if params[:post][:image].present?

      if @post.update(post_params)
        redirect_to post_path(@post), notice: t("defaults.flash_message.updated", item: Post.model_name.human), status: :see_other
      else
        flash.now[:alert] = t("defaults.flash_message.not_updated", item: Post.model_name.human)
        render :edit, status: :unprocessable_entity
      end

    rescue ImageProcessable::ImageProcessingError => e
      flash.now[:alert] = e.message
      render :edit
    end
  end

  def destroy
    @post.destroy!  # set_user_postで取得済みの@postを使う
    redirect_to posts_path, notice: t("defaults.flash_message.deleted", item: Post.model_name.human), status: :see_other
  end
  # HTTPステータスコード 303 "See Other" を送信

  def favorites
    @posts = current_user.favorite_posts
  end
  # お気に入りした投稿の一覧

  private

  def post_params
    params.require(:post).permit(:region, :shop_name, :rating, :body, :shop_id, :is_pr)
  end
  # :imageを追加(画像)

  def set_user_post
    @post = current_user.posts.find_by(id: params[:id])
    redirect_to posts_path, alert: t("defaults.errors.unauthorized_access") unless @post
  end

  def setup_shop
    return unless params[:post][:place_id].present?

    shop = Shop.find_or_create_by(place_id: params[:post][:place_id]) do |s|
      s.name = params[:post][:shop_name]
      s.address = params[:post][:address]
      s.google_map_url = params[:post][:google_map_url]
      s.phone_number = params[:post][:phone_number]
      s.business_hours = params[:post][:business_hours]
    end

    params[:post][:shop_id] = shop.id
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<!-- 新規投稿 -->
<!-- 入力フォーム -->
<%# local: true ← Turbo Drive で送信しない（通常の form 送信）%>
<%= form_with model: @post, local: true do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
    <div class="bg-secondary text-base p-4 pb-20 w-full">

      <!-- 都道府県 -->
      <div class="form-control mb-4">
        <%= f.label :region, class: "label-accent" do%>
          <%= f.object.class.human_attribute_name(:region) %><span>*</span>
        <% end %>
        <%= f.text_field :region, class: "input input-primary bg-neutral w-full", placeholder: "例: 東京都" %>
      </div>

      <!-- 店名 -->
      <div class="form-control mb-4 ">
        <%= f.label :shop_name, class: "label-accent" do%>
          <%= f.object.class.human_attribute_name(:shop_name) %><span>*</span>
        <% end %>
        <div class= "flex flex-col space-y-2">
          <%= f.text_field :shop_name, class: "input input-primary bg-neutral w-full", placeholder: "例: スターバックス渋谷店" %>
      
      <!-- 店舗詳細検索ボタン -->
          <button type="button" id="search_shop_btn" class="btn btn-primary text-neutral">
          店舗詳細
          </button>
        </div>
      </div>
      
      <!-- 検索結果の表示エリア JavaScriptで新規検索結果を表示する場所-->
      <div id="shop_result" class="mt-4"></div>

      <!-- 既に店舗情報が保存されている場合は表示 -->
      <% if @post.shop.present? %>
        <div id="existing_shop_info">
          <%= render 'shared/shop_info', shop: @post.shop, title: @post.shop_name + 'の店舗情報' %>
        </div>
      <% end %>

      <!-- 隠しフィールド：店舗詳細情報 -->
      <%= f.hidden_field :place_id, id: "post-place-id", value: @post.shop&.place_id %>
      <%= f.hidden_field :address, id: "post-address", value: @post.shop&.address %>
      <%= f.hidden_field :google_map_url, id: "post-map-url", value: @post.shop&.google_map_url %>
      <%= f.hidden_field :phone_number, id: "post-phone", value: @post.shop&.phone_number %>
      <%= f.hidden_field :business_hours, id: "post-hours", value: @post.shop&.business_hours %>
      <%# JavaScriptで検索して店舗を選ぶと、この隠しフィールドに値がセットされる
          フォーム送信時に、この隠しフィールドの値が一緒に送られてサーバーに保存される %>


      <!-- 評価 -->
      <div class="form-control mb-4">
        <%= f.label :rating, class: "label-accent" %>
          <div class="rating rating-lg flex space-x-2">
            <% %w[very_poor poor ordinary good excellent].each_with_index do |value, index| %>
            <%= f.radio_button :rating, index + 1,
                class: "mask mask-star-2 bg-accent",
                id: "rating_#{index + 1}" %>
            <% end %>
           </div>
      </div>

      <!-- PR -->
      <div class="form-control mb-4">
        <%= f.label :is_pr, class: "label-accent" do %>
        <%= f.check_box :is_pr, class: "checkbox checkbox-sm border-primary border-2"%>
          PR投稿の場合はチェックしてください
        <% end %>
      </div>



      <!-- 画像 -->
      <div class="form-control mb-4">
        <legend class="fieldset-legend font-normal">画像</legend>
          <%= f.file_field :image, class: "file-input file-input-primary file:text-neutral bg-neutral w-full",
                                   accept: Post::ACCEPTED_CONTENT_TYPES.join(',') %>
            <label class="label">
              <span class="text-xs md:text-sm">JPEG、PNG、GIF、WebP、HEIC形式（10MB以下）の画像</span>
            </label>
      </div>

      <!-- レビュー -->
      <div class="form-control mb-4">
        <%= f.label :body, class: "label-accent" %>
        <%= f.text_area :body, class: "textarea textarea-primary bg-neutral w-full", rows: "4", placeholder: "カフェの感想を書いてください..." %>
      </div>

      <!-- 投稿ボタン -->
      <div class="form-control mt-6">
        <%= f.submit t('.submit'), class: "btn btn-primary text-neutral w-full" %>
      </div>
    </div>
<% end %>

app/views/posts/_post.html.erb
 <!-- 投稿カード -->
<div class="card bg-neutral shadow-sm w-full mx-auto h-96">
  <div class="card-body p-6 flex flex-col h-full">
    <!-- ユーザー情報 -->
    <div class="flex items-center gap-2 text-xs">
      <!-- プロフィール画像 -->
      <div class="w-6 h-6 rounded-full overflow-hidden bg-neutral text-primary flex items-center justify-center">
          <% if post.user.profile_image.attached? %>
            <%= link_to profile_path(post.user) do %>
              <%= image_tag(post.user.profile_image, alt: "#{post.user.nickname.present? ? post.user.nickname : post.user.username}さんのプロフィール画像", class: "w-full h-full rounded-full object-cover") %>
            <% end %>
          <% else %>
            <%= link_to profile_path(post.user) do %>
              <svg xmlns="http://www.w3.org/2000/svg"
                viewBox="0 0 24 24" 
                fill="none" 
                stroke="currentColor" 
                stroke-width="2" 
                stroke-linecap="round" 
                stroke-linejoin="round"
                class="w-full h-full lucide lucide-circle-user-round-icon lucide-circle-user-round">
              <path d="M18 20a6 6 0 0 0-12 0"/>
              <circle cx="12" cy="10" r="4"/><circle cx="12" cy="12" r="10"/>
              </svg>
            <% end %>
          <% end %>
        </div>
      <!-- ユーザー名 -->
      <%= link_to truncate(post.user.nickname.presence || post.user.username, length: 12, omission: '...'), profile_path(post.user) %>
      <span class="text-accent/70"><%= post.created_at.strftime("%Y/%m/%d") %></span>
      <!-- PRバッジ -->
      <% if post.is_pr %>
        <span class="badge badge-secondary text-accent badge-sm rounded-2xl ml-auto">PR</span>
      <% end %>
    </div>

      <!-- 地域・店名 -->
      <div class="flex items-center gap-1 mt-2 h-5  text-base">
        <%= link_to post_path(post), class: "flex items-center gap-2 w-full hover:opacity-70 transition" do %>
          <svg class="size-[1.2em]" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><g fill="currentColor" stroke-linejoin="miter" stroke-linecap="butt"><polyline points="1 11 12 2 23 11" fill="none" stroke="currentColor" stroke-miterlimit="10" stroke-width="2"></polyline><path d="m5,13v7c0,1.105.895,2,2,2h10c1.105,0,2-.895,2-2v-7" fill="none" stroke="currentColor" stroke-linecap="square" stroke-miterlimit="10" stroke-width="2.5"></path><line x1="12" y1="22" x2="12" y2="18" fill="none" stroke="currentColor" stroke-linecap="square" stroke-miterlimit="10" stroke-width="2"></line></g></svg>
          <span class="whitespace-nowrap"><%= truncate(post.region, length: 4, omission: '') %></span>
          <span class="font-bold whitespace-nowrap overflow-hidden"><%= truncate(post.shop_name, length: 12, omission: '...') %></span>
        <% end %>
      </div>

    <!-- 画像エリア -->
    <div class="bg-gray-200 aspect-square w-full rounded mt-2 overflow-hidden">
      <% if post.image.attached? %>
        <%= image_tag(post.image, alt: "#{post.shop_name}の画像", class: "w-full h-full object-cover") %>
      <% else %>
        <%= image_tag("coffee.jpg", alt: "デフォルト画像", class: "w-full h-full object-cover") %>
     <% end %>
    </div>
    
    <!-- 評価と編集・削除アイコン -->
    <div class="flex justify-between">
      <!-- 評価 -->
      <div class="rating rating-sm">
        <% (1..5).each do |i| %>
          <input type="radio" class="mask mask-star-2 bg-primary" 
               disabled <%= 'checked' if i <= post.rating %> />
        <% end %>
      </div>

      <!-- 自分の投稿は編集アイコン、削除アイコン -->
      <% if user_signed_in? && current_user.own?(post) %>
        <div class="text-primary flex gap-1">
          <%= link_to edit_post_path(post), id: "button-edit-#{post.id}" do %>
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-pencil-icon lucide-pencil"><path d="M21.174 6.812a1 1 0 0 0-3.986-3.987L3.842 16.174a2 2 0 0 0-.5.83l-1.321 4.352a.5.5 0 0 0 .623.622l4.353-1.32a2 2 0 0 0 .83-.497z"/><path d="m15 5 4 4"/></svg>
          <% end %>
          <%= link_to post_path(post), id: "button-delete-#{post.id}", data: { turbo_method: :delete, turbo_confirm: t('defaults.delete_confirm') } do %>
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-trash-icon lucide-trash"><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6"/><path d="M3 6h18"/><path d="M8 6V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"/></svg>
          <% end %>
        </div>
      <% else %>
        <!-- 他の人の投稿はブックマークアイコン -->
          <%= render 'shared/favorite_buttons', { post: post } %>
      <% end %>
    </div>

  </div>
</div>

app/views/posts/_search_form.html.erb
<div class="flex gap-5 items-center">
<div class= 'w-full'>
<%= search_form_for search, url: url, data: { turbo: false } do |f| %>
  <%= f.search_field :region_or_shop_name_or_body_cont, class: 'input input-primary input-lg w-full bg-neutral', placeholder: t('defaults.search_word') %>
</div>
    <div class="form-control">
        <%= f.submit t('search_form.submit'), class: "btn btn-primary btn-lg btn-wide px-8 text-neutral " %>
    </div>
</div>
<% end %>

<%# 地域 or 店名 or 本文　の部分一致で検索%>
<%# qはposts_controllerで定義している %>
<%# data: { turbo: false }で押すたびにページが更新される  %>

app/views/posts/edit.html.erb
<%# 編集入力 %>
<div class="container mx-auto px-4 py-6">
  <h1 class="text-2xl font-bold mb-6"><%= t('.title') %></h1>
  <%= render 'form', post: @post %>
</div>

app/views/posts/index.html.erb
<!-- 投稿一覧 -->
<div class="container mx-auto px-4 py-6 pb-20">
  <%= render 'search_form', search: @search, url: posts_path %>

  <% if params[:q].present? && @posts.empty? %>
    <div class="text-center text-lg mt-6">
      <p><%= t('defaults.no_results') %></p>
    </div>
  <% else %>

  <!-- 投稿カードグリッド -->
  <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-5 px-2 mt-6">
    <%= render @posts %>
  </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<%# 新規投稿 %>
<div class="container mx-auto px-4 py-6">
  <h1 class="text-2xl font-bold mb-6"><%= t('.title') %></h1>
  <%= render 'form', post: @post %>
</div>

app/views/posts/show.html.erb
<!-- 投稿詳細 -->
<!-- 投稿カードグリッド -->
<div class="container mx-auto w-full px-4 sm:w-11/12 md:w-3/4 lg:w-2/3 xl:w-1/2 pt-5 pb-25">
  <div class="card bg-neutral shadow-sm w-full mx-auto">
    <div class="card-body p-6">
      <!-- ユーザー情報 -->
      <div class="flex items-center gap-3 mb-2">
        <!--  プロフィール画像 -->
        <div class="w-10 h-10 rounded-full overflow-hidden bg-neutral text-primary flex items-center justify-center">
          <% if @post.user.profile_image.attached? %>
            <%= link_to profile_path(@post.user) do %>
              <%= image_tag(@post.user.profile_image, alt: "#{@post.user.nickname.present? ? @post.user.nickname : @post.user.username}さんのプロフィール画像", class: "w-full h-full rounded-full object-cover") %>
            <% end %>
          <% else %>
            <%= link_to profile_path(@post.user) do %>
              <svg xmlns="http://www.w3.org/2000/svg"
                viewBox="0 0 24 24" 
                fill="none" 
                stroke="currentColor" 
                stroke-width="2" 
                stroke-linecap="round" 
                stroke-linejoin="round"
                class="w-full h-full lucide lucide-circle-user-round-icon lucide-circle-user-round">
                <path d="M18 20a6 6 0 0 0-12 0"/>
                <circle cx="12" cy="10" r="4"/><circle cx="12" cy="12" r="10"/>
              </svg>
          <% end %>
          <% end %>
        </div>
        <!--  プロフィール画像 -->
        <div class="flex flex-col flex-1 min-w-0">
          <%= link_to profile_path(@post.user) do %>
            <span class="font-medium break-words">
              <%= @post.user.nickname || @post.user.username %>
            </span>
          <% end %>
          <span class="text-accent/70 text-xs mt-1">
            <%= @post.created_at.strftime("%Y/%m/%d %H:%M") %>
          </span>
        </div>

         <!-- 自分の投稿は編集・削除アイコン -->
         <% if user_signed_in? && current_user.own?(@post) %>
           <div class="flex gap-1">
             <%= link_to edit_post_path(@post), id: "button-edit-#{@post.id}" do %>
               <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-pencil-icon lucide-pencil"><path d="M21.174 6.812a1 1 0 0 0-3.986-3.987L3.842 16.174a2 2 0 0 0-.5.83l-1.321 4.352a.5.5 0 0 0 .623.622l4.353-1.32a2 2 0 0 0 .83-.497z"/><path d="m15 5 4 4"/></svg>
             <% end %>
             <%= link_to post_path(@post), id: "button-delete-#{@post.id}", data: { turbo_method: :delete, turbo_confirm: t('defaults.delete_confirm') } do %>
               <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-trash-icon lucide-trash"><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6"/><path d="M3 6h18"/><path d="M8 6V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"/></svg>
             <% end %>
           </div>

          <% else %>
          <!-- 他の人の投稿はブックマークアイコン -->
          <%= render 'shared/favorite_buttons', { post: @post } %>
         <% end %>
         <!-- PRバッジ -->
        <% if @post.is_pr %>
          <span class="badge badge-secondary text-accent badge-base rounded-2xl">PR</span>
        <% end %>
      </div>
      
    <div class= "flex justify-between">
      <!-- 地域・店名 -->
      <div class="flex flex-col gap-0.5 mb-2">
        <div class="flex items-center gap-1.5">
          <svg class="size-[1em] text-base-content/60 flex-shrink-0" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
            <path d="M21 10c0 7-9 13-9 13s-9-6-9-13a9 9 0 0 1 18 0z"></path>
            <circle cx="12" cy="10" r="3"></circle>
          </svg>
          <span class="text-sm text-base-content/60"><%= @post.region %></span>
        </div>
        <div class="flex items-center gap-2">
          <svg class="size-[1.2em] flex-shrink-0" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
            <g fill="currentColor" stroke-linejoin="miter" stroke-linecap="butt">
              <polyline points="1 11 12 2 23 11" fill="none" stroke="currentColor" stroke-miterlimit="10" stroke-width="2.5"></polyline>
               <path d="m5,13v7c0,1.105.895,2,2,2h10c1.105,0,2-.895,2-2v-7" fill="none" stroke="currentColor" stroke-linecap="square" stroke-miterlimit="10" stroke-width="2"></path>
              <line x1="12" y1="22" x2="12" y2="18" fill="none" stroke="currentColor" stroke-linecap="square" stroke-miterlimit="10" stroke-width="2"></line>
            </g>
          </svg>
          <span class="font-bold text-lg"><%= @post.shop_name %></span>
        </div>
      </div>

      <!-- 右側：Xシェアボタン -->
        <%= link_to "https://twitter.com/share?url=#{post_url(@post)}&text=【#{@post.region}のカフェ好き必見☕️】%0a hoshi cafeで#{@post.shop_name}の投稿をチェック！%0a &hashtags=カフェ,#{@post.region}カフェ,hoshicafe",
            target: '_blank', #リンクを新しいウィンドウまたはタブで開く
            class: "btn btn-sm bg-primary text-neutral" do %>
              <svg aria-label="X logo" width="16" height="12" viewBox="0 0 300 271" xmlns="http://www.w3.org/2000/svg">
              <path fill="currentColor" d="m236 0h46l-101 115 118 156h-92.6l-72.5-94.8-83 94.8h-46l107-123-113-148h94.9l65.5 86.6zm-16.1 244h25.5l-165-218h-27.4z"/>
              </svg>
              Xでシェア
        <% end %>
    </div>

      <!-- 画像エリア -->
      <div class="flex justify-center w-full rounded overflow-hidden mb-2">
        <% if @post.image.attached? %>
          <%= image_tag(@post.image, alt: "#{@post.shop_name}の画像", class: "max-w-full h-auto object-cover") %>
        <% else %>
          <%= image_tag("coffee.jpg", alt: "デフォルト画像", class: "w-full h-auto object-cover") %>
        <% end %>
      </div>
      
      <!-- 評価 -->
      <div class="rating rating-sm">
        <% (1..5).each do |i| %>
          <input type="radio" class="mask mask-star-2 bg-primary"
                 disabled <%= 'checked' if i <= @post.rating %> />
        <% end %>
      </div>

      <!-- 店舗詳細情報の表示エリア -->
      <% if @post.shop %>
        <%= render 'shared/shop_info', shop: @post.shop, title: @post.shop.name + 'の店舗情報' %>
      <% end %>

      <!-- 本文 -->
      <div class="text-base break-words leading-normal" style="white-space: pre-line; margin-top: -20px;">
        <%= @post.body.strip %>
      </div>

      <!-- 他の人の投稿はブックマークアイコン -->
    </div>
  </div>
</div>